sudo: required
services:
        - docker
before_install:
        - docker build -t samratmitra/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run samratmitra/react-test npm test -- --coverage
after_success:
        - docker build -t samratmitra/multi-client ./client
        - docker build -t samratmitra/multi-nginx ./nginx
        - docker build -t samratmitra/multi-server ./server
        - docker build -t samratmitra/multi-worker ./worker
        # Log in to DockerCLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        # Take those images and push them to docker hub
        - docker push samratmitra/multi-client
        - docker push samratmitra/multi-nginx
        - docker push samratmitra/multi-server
        - docker push samratmitra/multi-worker


